name: Search Discussions in Organization

on:
  workflow_dispatch:
    inputs:
      ORG:
        description: 'The organization name'
        required: true
      AUTHOR:
        description: 'The GitHub username of the author'
        required: true

jobs:
  search_discussions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install octokit

      - name: Search discussions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: ${{ github.event.inputs.ORG }}
          AUTHOR: ${{ github.event.inputs.AUTHOR }}
        run: |
          ruby search_discussions.rb
